### ISSUE TITLE
integration with helm-projectile

### ISSUE THREAD

**Issue by Pitometsu** [waymondo/ace-jump-buffer#10]
There r unnecessary \*helm\* buffers
![ajb screenshot](http://i.imgur.com/3hEw6xM.png)
![helm-projectile screenshot](http://i.imgur.com/zs1mcL8.png)

**Comment by waymondo** [comment]
I am not a `helm-projectile` user so I don't know what makes the most sense for your setup. `(ace-jump-projectile-buffers)` simply limits the buffers to all those in your current project, which includes your `*helm*` buffers.

You can always use the [macro](https://github.com/waymondo/ace-jump-buffer#macro) to create your own `ace-jump-buffer` functions. You [can see that `(ace-jump-projectile-buffers)`](https://github.com/waymondo/ace-jump-buffer/blob/master/ace-jump-buffer.el#L174-L178) is actually created with this macro, so you could do something like:

``` elisp
(make-ace-jump-buffer-function "projectile-no-helm"
  (let ((project-root (projectile-project-root)))
    (with-current-buffer buffer
      (or (not (projectile-project-buffer-p buffer project-root))
          (string-match "helm" (buffer-name buffer))))))
```

This would create `(ace-jump-projectile-no-helm-buffers)` which would limit buffers to your current project and exclude all buffers that contain `helm` in the name.

**Comment by Pitometsu** [comment]
Thank you for solution
