### ISSUE TITLE
an option for ignoring some buffers

### ISSUE THREAD

**Issue by llcc** [waymondo/ace-jump-buffer#11]
When I call ace-jump-buffer, some buffers like helm temporary buffers, compilation buffer got the place of buffer list, which sometimes is annoying if number of my buffers is large. 

So can you define a variable for exempt these kind of buffers? Thanks ahead of times.

**Comment by llcc** [comment]
sorry for inconvenience, I found the variable `ajb-bs-configuration`, problem solved.

**Comment by waymondo** [comment]
No worries. Here's another similar approach of tricking out your own custom `defun`:

https://github.com/waymondo/ace-jump-buffer/issues/10#issuecomment-88302859
