### ISSUE TITLE
Please specify the license for you Emacs packages

### ISSUE THREAD

**Issue by tarsius** [waymondo/ace-jump-buffer#13]
Could you please specify the license used by your Emacs packages?

Assuming that you want to release under "the GPL v3 or any later version", the best way to do that would be to add this to the library header:

```
;; This file is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 3, or (at your option)
;; any later version.

;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

You could also, or instead, add a `LICENSE` file containing the text of the GPL-3. But if you only add that file, then the "or (at your option) any later version" bit won't be known.

If this is too noisy for you, then you could also add one of these lines to the header:

```
;; License: GNU General Public License version 3, or (at your option) any later version
;; License: GNU General Public License version 3, or any later version
;; License: GNU GPL version 3, or (at your option) any later version
;; License: GPL version 3, or (at your option) any later version
;; License: GPL version 3, or any later version
;; License: GPL v3, or (at your option) any later version
;; License: GPL v3, or any later version
;; License: GPL-3+
```

These are your packages I am aware of that don't specify their license: `ace-jump-buffer`, `ace-jump-zap`, `apropospriate-theme`, `ido-exit-target`, `projector`, and `use-package-chords`.

**Comment by waymondo** [comment]
Cool, thanks for bringing this to my attention.
