### ISSUE TITLE
Ace-jump buffer with predefined characters

### ISSUE THREAD

**Issue by ReneFroger** [waymondo/ace-jump-buffer#9]
Hi there!

Thanks for sharing this nice extension. However, I have a question. 

I don't often have many buffers open. So I wonder if it would be possible to have my prefered keys come first. Usually it will be the keys on the home row first (`asdfghjkl`), instead alphabetically. This makes me less move my fingers to the keys, because they're already on the home row. 

Ace-jump knows the same option: https://github.com/winterTTr/ace-jump-mode/wiki/AceJump-FAQ

Is that possible for ace-jump-buffer too?

**Comment by waymondo** [comment]
great idea! just added this. you can enable by setting `(setq ajb-home-row-keys t)` in your config. it will work best with `ajb-max-window-height` set to 20 or less. (20 is the new default)

**Comment by ReneFroger** [comment]
Just tried it out, and it worked fine! Thanks for that!
